name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and update AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CLI_TOKEN }}" > ~/.aws/credentials

      - name: Set up kubectl
        run: |
          sudo snap install kubectl --classic
          
      - name: Connect to EKS cluster
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-cluster
          kubectl get nodes -o wide
